name: Call Trivy
on:
 push:
   branches: [main]
 pull_request:
jobs:
 scan:
   name: Scan
   uses: warcraft2/actions/.github/workflows/reusable-trivy.yml@reusable-trivy
    with:
      image: 'ghcr.io/warcraft2/wordsmith-web:latest'
